export const DASHBOARD_OFFLINE_THRESHOLD_MS = 14_000;

export const DASHBOARD_USAGE_WARN_THRESHOLD = 60;
export const DASHBOARD_USAGE_DANGER_THRESHOLD = 90;

export const DASHBOARD_REQUEST_TIMEOUT_MS = 3000;
export const DASHBOARD_POLL_INTERVAL_MS = 3000;
